### ISSUE TITLE
Illegal division by zero at RestrictionDigest.pm line 1502 

### ISSUE THREAD

**Issue by csjlee** [JINPENG-WANG/RestrictionDigest#6]
under #Summary of the whole reference genome.
line 1502: my $overall_all_type_coverage=$overall_fragments_length/$overall_length_of_scfd; 

this gets the Illegal division by zero at RestrictionDigest.pm line 1502 error code.

**Comment by JINPENG-WANG** [comment]
Could you paste your command as well as the content of you input file here?

**Comment by csjlee** [comment]
Hello,

I’ve changed the way I run the code. I believe it works now, but I get a new error code. Could you please help me with the following? :

This is my script:
use 5.006;
use strict;
use warnings FATAL => "all";
use ExtUtils::MakeMaker;

use RestrictionDigest;
my $double_digest=RestrictionDigest::SingleItem::Double->new();
$double_digest->add_ref(-reference =>"/Volumes/Seagate/Restriction/RestrictionDigest-master/adzukireferencegenome.fasta");
$double_digest->add_enzyme_pair(-front_enzyme =>"XbaI", -behind_enzyme =>"PstI");
$double_digest->change_range(-start =>250,-end =>450);
$double_digest->change_lengths_distribution_parameters(-front =>200,-behind =>800,-step =>25);
$double_digest->add_output_dir(-output_dir=>"/Volumes/Seagate/Restriction/RestrictionDigest-master/output/18");
$double_digest->double_digest();
$double_digest->add_gff(-gff => "/Volumes/Seagate/Restriction/RestrictionDigest-master/GCF_001190045.1_Vigan1.1_genomic.gff");
$double_digest->frags_in_range_coverage();

and I get the error: Illegal division by zero at /Users/christine/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/RestrictionDigest.pm line 2966, <GEN15> line 5324832.

This is the whole script running: It appears it runs, I want to ask, is the information generated negatively affected by the error or is the output still usable for my analysis?
The reference file User provides is:	adzukireferencegenome.fasta
The front restrict endonuclease User provides is:	XbaI
The behind restrict endonuclease User provides is:	MspI
The seperate range of the fragments User wants to output is:	250 to 450 bp.
The output directory User provides is:	/Volumes/Seagate/Restriction/RestrictionDigest-master/output/16
Digesting >NC_030637.1 Vigna angularis cultivar Jingnong 6 chromosome 1, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030638.1 Vigna angularis cultivar Jingnong 6 chromosome 2, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030639.1 Vigna angularis cultivar Jingnong 6 chromosome 3, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030640.1 Vigna angularis cultivar Jingnong 6 chromosome 4, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030641.1 Vigna angularis cultivar Jingnong 6 chromosome 5, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030642.1 Vigna angularis cultivar Jingnong 6 chromosome 6, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030643.1 Vigna angularis cultivar Jingnong 6 chromosome 7, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030644.1 Vigna angularis cultivar Jingnong 6 chromosome 8, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030645.1 Vigna angularis cultivar Jingnong 6 chromosome 9, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030646.1 Vigna angularis cultivar Jingnong 6 chromosome 10, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030647.1 Vigna angularis cultivar Jingnong 6 chromosome 11, Vigan1.1, whole genome shotgun sequence...	Done!
The GFF file provided is	GCF_001190045.1_Vigan1.1_genomic.gff.
Reading the GFF file...	Done!
Reading the positions file...	Done!
Coverage: Processing NC_030637.1 Vigna angularis cultivar Jingnong 6 chromosome 1, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030638.1 Vigna angularis cultivar Jingnong 6 chromosome 2, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030639.1 Vigna angularis cultivar Jingnong 6 chromosome 3, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030640.1 Vigna angularis cultivar Jingnong 6 chromosome 4, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030641.1 Vigna angularis cultivar Jingnong 6 chromosome 5, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030642.1 Vigna angularis cultivar Jingnong 6 chromosome 6, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030643.1 Vigna angularis cultivar Jingnong 6 chromosome 7, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030644.1 Vigna angularis cultivar Jingnong 6 chromosome 8, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030645.1 Vigna angularis cultivar Jingnong 6 chromosome 9, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030646.1 Vigna angularis cultivar Jingnong 6 chromosome 10, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030647.1 Vigna angularis cultivar Jingnong 6 chromosome 11, Vigan1.1, whole genome shotgun sequence...	Done!
Illegal division by zero at /Users/christine/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/RestrictionDigest.pm line 2966, <GEN15> line 5324832.
Christines-MacBook-Air-2:RestrictionDigest-master christine$ perl tryrestriction.pl
The reference file User provides is:	adzukireferencegenome.fasta
The front restrict endonuclease User provides is:	XbaI
The behind restrict endonuclease User provides is:	PstI
The seperate range of the fragments User wants to output is:	250 to 450 bp.
The output directory User provides is:	/Volumes/Seagate/Restriction/RestrictionDigest-master/output/17
Digesting >NC_030637.1 Vigna angularis cultivar Jingnong 6 chromosome 1, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030638.1 Vigna angularis cultivar Jingnong 6 chromosome 2, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030639.1 Vigna angularis cultivar Jingnong 6 chromosome 3, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030640.1 Vigna angularis cultivar Jingnong 6 chromosome 4, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030641.1 Vigna angularis cultivar Jingnong 6 chromosome 5, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030642.1 Vigna angularis cultivar Jingnong 6 chromosome 6, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030643.1 Vigna angularis cultivar Jingnong 6 chromosome 7, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030644.1 Vigna angularis cultivar Jingnong 6 chromosome 8, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030645.1 Vigna angularis cultivar Jingnong 6 chromosome 9, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030646.1 Vigna angularis cultivar Jingnong 6 chromosome 10, Vigan1.1, whole genome shotgun sequence...	Done!
Digesting >NC_030647.1 Vigna angularis cultivar Jingnong 6 chromosome 11, Vigan1.1, whole genome shotgun sequence...	Done!
The GFF file provided is	GCF_001190045.1_Vigan1.1_genomic.gff.
Reading the GFF file...	Done!
Reading the positions file...	Done!
Coverage: Processing NC_030637.1 Vigna angularis cultivar Jingnong 6 chromosome 1, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030638.1 Vigna angularis cultivar Jingnong 6 chromosome 2, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030639.1 Vigna angularis cultivar Jingnong 6 chromosome 3, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030640.1 Vigna angularis cultivar Jingnong 6 chromosome 4, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030641.1 Vigna angularis cultivar Jingnong 6 chromosome 5, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030642.1 Vigna angularis cultivar Jingnong 6 chromosome 6, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030643.1 Vigna angularis cultivar Jingnong 6 chromosome 7, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030644.1 Vigna angularis cultivar Jingnong 6 chromosome 8, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030645.1 Vigna angularis cultivar Jingnong 6 chromosome 9, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030646.1 Vigna angularis cultivar Jingnong 6 chromosome 10, Vigan1.1, whole genome shotgun sequence...	Done!
Coverage: Processing NC_030647.1 Vigna angularis cultivar Jingnong 6 chromosome 11, Vigan1.1, whole genome shotgun sequence...	Done!
Illegal division by zero at /Users/christine/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/RestrictionDigest.pm line 2966, <GEN15> line 5324832.

**Comment by JINPENG-WANG** [comment]
Hi, that was a bug. I have fixed it. You can download the updated module and try agian. 
Thanks for reporting the problem!
