### ISSUE TITLE
can this program be used in the 2b-RAD sequencing?  BsaXI enzyme used?

### ISSUE THREAD

**Issue by wsai0219** [JINPENG-WANG/RestrictionDigest#9]
as the title said.

**Comment by JINPENG-WANG** [comment]
The current version  of the program is not suitable for enzymes used in 2b-RAD method. Not work for BsaXI.

**Comment by JINPENG-WANG** [comment]
> as the title said.

Hello. Recently, I updated the module and made it compatible with enzymes often used in 2b-RAD sequencings, like BsaXI.  As BsaXI cuts the DNA sequence at two different sites, users need to use two pseudo restriction enzymes to simulate the BsaXI enzyme.  Below is an example:

1. List the cutting sites of BsaXI: N|NNNNNNNNNACNNNNNCTCCNNNNNNNNNN|N.
2. Make the first pseudo enzyme cut at the front cutting-site, for example we name it BsaXIF, and its cutting site is:  N|NNNNNNNNNACNNNNNCTCCN.
3. Make the second pseudo enzyme cut at the behind cutting-site, for example we name it as BsaXIB, and its cutting site is: NACNNNNNCTCCNNNNNNNNNN|N. 
4. Add the two pseudo enzymes to the module and use them to perform double-enzyme digest.

```
#!/usr/bin/perl -w 
  use strict; 
  use IO::File; 
  use lib "./"; 
  use RestrictionDigest; 
  my $dg = RestrictionDigest::SingleItem::Double->new();  
  $dg->add_ref(-reference=>"example.reference.fa"); 
  $dg->new_enzyme(-enzyme_name=>'BsaXIF', -recognition_site=>'N|NNNNNNNNNACNNNNNCTCCN'); 
  $dg->new_enzyme(-enzyme_name=>'BsaXIB', -recognition_site=>'NACNNNNNCTCCNNNNNNNNNN|N'); 
  $dg->add_enzyme_pair(-front_enzyme=>"BsaXIF",-behind_enzyme=>'BsaXIB'); 
  $dg->add_output_dir(-output_dir=>"output"); 
  $dg->double_digest(); 
```

But keep in mind that 2b-RAD enzymes can cut DNA sequences into small pieces, so the program will need large memory space. So it is best to run it in a computer with large memory space or in a cluster with enough memory. If memory space is not available, consider cutting chromosomes or scaffolds into smaller ones.

**Comment by JINPENG-WANG** [comment]
Updates have been made to RestrictionDigest to allow 2b-RAD enzymes can be used. Try it with the most recent version of RestrictionDigest.
